In [1]:
"""1. Create a vector (array) of 1XN dimension representing N-
dimensional feature vector of a sample. Write a program to

compute the mean and variance of the elements present in the
array."""
import numpy as np

def compute_mean_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

# Example vector creation
N = 10  # Define the dimensionality of the vector
sample_vector = np.random.rand(1, N)  # Creating a random vector of shape 1xN

# Compute mean and variance
mean, variance = compute_mean_variance(sample_vector)

print("Sample Vector:", sample_vector)
print("Mean:", mean)
print("Variance:", variance)

Sample Vector: [[0.69401737 0.44205247 0.11994338 0.08865997 0.31086373 0.43871252
  0.11284859 0.34318291 0.85334886 0.46731457]]
Mean: 0.3870944383122842
Variance: 0.05670978979255773


In [2]:
"""2. Create two vectors each of dimension 1XM each representing N-
dimensional feature vector of a sample. Write a program to
compute the Covariance between them."""

import numpy as np

def compute_covariance(vector1, vector2):
    covariance_matrix = np.cov(vector1, vector2)
    covariance = covariance_matrix[0, 1]  # Extracting the covariance value from the covariance matrix
    return covariance

# Example vectors creation
M = 5  # Define the dimensionality of the vectors
sample_vector1 = np.random.rand(1, M)  # Creating a random vector of shape 1xM
sample_vector2 = np.random.rand(1, M)  # Creating another random vector of shape 1xM

# Compute covariance
covariance = compute_covariance(sample_vector1, sample_vector2)

print("Sample Vector 1:", sample_vector1)
print("Sample Vector 2:", sample_vector2)
print("Covariance between vectors:", covariance)

Sample Vector 1: [[0.87000271 0.02114919 0.29856317 0.36521721 0.95250679]]
Sample Vector 2: [[0.77858346 0.65305924 0.18884423 0.9364002  0.5190719 ]]
Covariance between vectors: 0.010354084403648016


In [3]:
"""3.Create two vectors each of dimension 1XN. Write a program to
compute the Correlation between them."""
import numpy as np

# Function to compute correlation
def compute_correlation(vector1, vector2):
    # Compute means
    mean1 = np.mean(vector1)
    mean2 = np.mean(vector2)
    
    # Compute standard deviations
    std_dev1 = np.std(vector1)
    std_dev2 = np.std(vector2)
    
    # Compute covariance
    covariance = np.mean((vector1 - mean1) * (vector2 - mean2))
    
    # Compute correlation
    correlation = covariance / (std_dev1 * std_dev2)
    
    return correlation

# Example vectors (replace these with your own vectors)
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([5, 4, 3, 2, 1])

# Compute correlation
corr = compute_correlation(vector1, vector2)
print("Correlation between the two vectors:", corr)

Correlation between the two vectors: -0.9999999999999998


In [4]:
"""4.Create a Matrix of MXN dimension representing the M-dimensional
feature vector for N number of samples i. e (i,j)th entry of the matrix
represents the ith feature of jth sample. Write a program to compute
the covariance matrix and correlation matrix. Comment on
takeaways from these matrixes."""

import numpy as np

# Function to compute covariance matrix
def compute_covariance_matrix(matrix):
    return np.cov(matrix)

# Function to compute correlation matrix
def compute_correlation_matrix(matrix):
    return np.corrcoef(matrix)

# Example matrix (replace this with your own matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute covariance matrix
cov_matrix = compute_covariance_matrix(matrix)
print("Covariance Matrix:")
print(cov_matrix)

# Compute correlation matrix
corr_matrix = compute_correlation_matrix(matrix)
print("\nCorrelation Matrix:")
print(corr_matrix)

Covariance Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
